### PR TITLE
Peer to peer code Review

### PR DESCRIPTION
**Pull request by kkasaija**
- [x] Implement a function for `adding` a new task
- [x] Implement a function for `editing` a task
- [x] Implement a function for `deleting` a task
- [x] All changes to the To Do List should be saved in `local storage`
- [x] Add interactive `check` buttons 
- [x] Add event listener to the `checkbox` (change).
- [x] Implement a function for the `"Clear all completed" button` (use filter() method).

### CODE REVIEW

**Comment by lolashot** [comment]
## Hi @Kasaija-Kenneth, Good Job! 👍👍 You are almost there! However, there are still some changes you need to make.

### **I will suggest that you remove all `console.log` from your code because this is not the best practice according to W3School javascript best practices**.

**Comment by Kasaija-Kenneth** [comment]
All requested changes i.e remove the 'console.log' statements have been removed.

**Comment by lolashot** [comment]
Hi @Kasaija-Kenneth,

  **Good Job on making the Required Changes, there is nothing else to say other than to say Its time to merge** 🙌 

**Congratulations 👍👍👍👍**

**Keep Rocking!**

**Comment by Kasaija-Kenneth** [comment]
THankyou for all the help towards making me a better programmer.

**Pull request merged**
